"use client"

import { useState } from 'react'

const SERVICE_OPTIONS = ['service1', 'service2', 'service3'] as const

type TestEntry = {
  id: string
  label: string
  success: boolean
  message: string
}

function createWebhookId(prefix: string) {
  return `${prefix}-${Date.now()}-${Math.random().toString(36).slice(2)}`
}

export default function TestToolsPage() {
  const [status, setStatus] = useState<string | null>(null)
  const [logEntries, setLogEntries] = useState<TestEntry[]>([])
  const [busy, setBusy] = useState(false)

  const addLog = (entry: TestEntry) => {
    setLogEntries((current) => [entry, ...current])
  }

  const handleWebhookReset = async () => {
    setBusy(true)
    setStatus('Sending one webhook event to reset provider quota...')
    const webhookId = createWebhookId('reset')

    try {
      const response = await fetch('/api/test-tools/webhook', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ webhookId }),
      })
      const payload = await response.json()
      const success = response.ok

      addLog({
        id: webhookId,
        label: 'Reset quota',
        success,
        message: success
          ? `Webhook processed. resetApplied=${payload.resetApplied}`
          : payload.error ?? 'Unknown error',
      })
      setStatus(success ? 'Quota reset webhook processed.' : 'Quota reset webhook failed.')
    } catch (error) {
      addLog({
        id: webhookId,
        label: 'Reset quota',
        success: false,
        message: error instanceof Error ? error.message : 'Request failed',
      })
      setStatus('Failed to call webhook.')
    } finally {
      setBusy(false)
    }
  }

  const handleWebhookIdempotency = async () => {
    setBusy(true)
    setStatus('Calling the same webhook event multiple times...')
    const webhookId = createWebhookId('idempotent')

    try {
      const calls = Array.from({ length: 3 }, (_, index) =>
        fetch('/api/test-tools/webhook', {
          method: 'POST',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify({ webhookId }),
        }).then(async (response) => ({
          response,
          body: await response.json(),
          index,
        })),
      )

      const results = await Promise.all(calls)
      results.forEach(({ response, body, index }) => {
        addLog({
          id: `${webhookId}-${index}`,
          label: `Idempotency call ${index + 1}`,
          success: response.ok,
          message: response.ok
            ? `Status ok, resetApplied=${body.resetApplied}`
            : body.error ?? `HTTP ${response.status}`,
        })
      })

      setStatus('Idempotency test complete.')
    } catch (error) {
      addLog({
        id: webhookId,
        label: 'Idempotency test',
        success: false,
        message: error instanceof Error ? error.message : 'Request failed',
      })
      setStatus('Idempotency test failed.')
    } finally {
      setBusy(false)
    }
  }

  const handleGenerateLeads = async () => {
    setBusy(true)
    setStatus('Generating 10 leads concurrently...')
    const base = Date.now()

    try {
      const requests = Array.from({ length: 10 }, (_, index) => {
        const phone = `900000${String(base % 1000000).padStart(6, '0')}${String(index).padStart(2, '0')}`
        const payload = {
          name: `Test Lead ${index + 1}`,
          phone,
          city: 'TestVille',
          service: SERVICE_OPTIONS[index % SERVICE_OPTIONS.length],
          description: 'Generated by concurrency test',
        }

        return fetch('/api/leads', {
          method: 'POST',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify(payload),
        }).then(async (response) => ({
          response,
          body: await response.json(),
          index,
        }))
      })

      const results = await Promise.all(requests)
      results.forEach(({ response, body, index }) => {
        addLog({
          id: `lead-${base}-${index}`,
          label: `Lead ${index + 1}`,
          success: response.ok,
          message: response.ok
            ? `Lead created with id=${body.id}`
            : body.error ?? `HTTP ${response.status}`,
        })
      })

      setStatus('Lead generation complete.')
    } catch (error) {
      addLog({
        id: `leadgen-${base}`,
        label: 'Generate leads',
        success: false,
        message: error instanceof Error ? error.message : 'Request failed',
      })
      setStatus('Lead generation failed.')
    } finally {
      setBusy(false)
    }
  }

  return (
    <main className="p-6">
      <div className="mb-6">
        <h1 className="text-2xl font-semibold">Test Tools</h1>
        <p className="text-sm text-slate-600 mt-2">
          This page is for manual testing only. The webhook route is separate from normal application flows.
        </p>
      </div>

      <div className="grid gap-4 sm:grid-cols-3">
        <button
          type="button"
          onClick={handleWebhookReset}
          disabled={busy}
          className="rounded-lg bg-sky-600 px-4 py-3 text-white transition hover:bg-sky-700 disabled:cursor-not-allowed disabled:bg-slate-300"
        >
          Reset provider quota to 10
        </button>
        <button
          type="button"
          onClick={handleWebhookIdempotency}
          disabled={busy}
          className="rounded-lg bg-emerald-600 px-4 py-3 text-white transition hover:bg-emerald-700 disabled:cursor-not-allowed disabled:bg-slate-300"
        >
          Call webhook multiple times
        </button>
        <button
          type="button"
          onClick={handleGenerateLeads}
          disabled={busy}
          className="rounded-lg bg-violet-600 px-4 py-3 text-white transition hover:bg-violet-700 disabled:cursor-not-allowed disabled:bg-slate-300"
        >
          Generate 10 leads instantly
        </button>
      </div>

      <div className="mt-6 rounded-lg border border-slate-200 bg-white p-4 shadow-sm">
        <h2 className="text-lg font-medium">Activity</h2>
        {status && <p className="mt-2 text-slate-700">{status}</p>}
        {logEntries.length === 0 ? (
          <p className="mt-4 text-sm text-slate-500">No activity yet.</p>
        ) : (
          <ul className="mt-4 space-y-3">
            {logEntries.map((entry) => (
              <li key={entry.id} className="rounded-lg border border-slate-200 p-3">
                <div className="flex items-center justify-between gap-3">
                  <div>
                    <p className="font-medium">{entry.label}</p>
                    <p className="text-sm text-slate-500">{entry.message}</p>
                  </div>
                  <span
                    className={`rounded-full px-2 py-1 text-xs font-semibold ${
                      entry.success ? 'bg-emerald-100 text-emerald-700' : 'bg-rose-100 text-rose-700'
                    }`}
                  >
                    {entry.success ? 'OK' : 'FAIL'}
                  </span>
                </div>
              </li>
            ))}
          </ul>
        )}
      </div>
    </main>
  )
}
